version: '3.12.3'

services:
  flask_backend:
    build: .
    container_name: web-forsikatel-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16.6
    container_name: postgres-forsikatel-db
    restart: always
    environment:
      POSTGRES_USER: forsikatel_web_db
      POSTGRES_PASSWORD: ForsikatelGTAKTI
      POSTGRES_DB: forsikatel_web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
