"""minor update on data model created at and updated at

Revision ID: 370c209da5d3
Revises: 9ee6775a5737
Create Date: 2025-02-20 14:17:51.595918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370c209da5d3'
down_revision: Union[str, None] = '9ee6775a5737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ubah default nilai last_juz dan total_khatam
    op.alter_column("data", "last_juz", server_default="0")
    op.alter_column("data", "total_khatam", server_default="0")
    
    op.alter_column("data", "created_at", server_default=sa.text("timezone('Asia/Jakarta', now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("data", "last_juz", server_default=None)
    op.alter_column("data", "total_khatam", server_default=None)
    op.alter_column("data", "created_at", server_default=None)
    # ### end Alembic commands ###
