"""Add channel and title column for hadits_kultum table

Revision ID: 9ee6775a5737
Revises: b518d653ce2c
Create Date: 2025-02-19 09:55:58.556256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee6775a5737'
down_revision: Union[str, None] = 'b518d653ce2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadist_kultum', sa.Column('title', sa.String(length=255), nullable=False, server_default='Default Title'))
    op.add_column('hadist_kultum', sa.Column('channel', sa.String(length=255), nullable=False, server_default='Default Title'))
    # Jika ingin menghapus default value setelah migrasi
    op.alter_column('hadist_kultum', 'title', server_default=None)
    op.alter_column('hadist_kultum', 'channel', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hadist_kultum', 'channel')
    op.drop_column('hadist_kultum', 'title')
    # ### end Alembic commands ###
